dist: trusty
sudo: required
language: python
python: "2.7"

services:
  - docker

env:
- ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH:$PWD/apb/roles

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

install:
  - pip install ansible
  - ansible-galaxy install -r apb/requirements-travis.yml
  - ansible-playbook apb/playbooks/provision.yml --syntax-check

script:
  - cd apb && docker build -t openshiftapb/starter-workshop-apb:$TRAVIS_COMMIT .

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag openshiftapb/starter-workshop-apb:$TRAVIS_COMMIT openshiftapb/starter-workshop-apb:$TAG
  - docker push openshiftapb/starter-workshop-apb:$TAG
